server:
  port: 10086
  servlet:
    application-display-name: SpringSecurityDemo

spring:
  datasource:
    url: jdbc:mysql://192.168.200.10:3306/security?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: test@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: 192.168.200.10
    port: 6379
    lettuce:
      pool:
        max-active: 100
        max-wait: -1ms
        max-idle: 8
        min-idle: 1
    timeout: PT10S

#Mapper.xml文件路径
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml